name: NAStool Docker
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - version.py
      - .github/workflows/build.yml
      - package_list.txt
      - requirements.txt
      - docker/Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Docker Image
    steps:
      -
        name: Checkout
        uses: actions/checkout@master

      -
        name: Release version
        id: release_version
        run: |
          app_version=$(cat version.py |sed -ne "s/APP_VERSION\s=\s'v\(.*\)'/\1/gp")
          echo "app_version=$app_version" >> $GITHUB_ENV

      -
        name: Set Up QEMU
        uses: docker/setup-qemu-action@v1

      -
        name: Set Up Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Login DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Init Python 3.10.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.10'

      -
        name: 使用官方 PyPI 镜像
        run: |
          sed -i 's|pip install --upgrade pip setuptools wheel|pip install -i https://pypi.org/simple --upgrade pip setuptools wheel|g' docker/Dockerfile
          sed -i 's|pip install cython|pip install -i https://pypi.org/simple cython|g' docker/Dockerfile
          sed -i 's|pip install -r https://raw.githubusercontent.com/jackloves111/9/refs/heads/master/requirements.txt|pip install -i https://pypi.org/simple -r https://raw.githubusercontent.com/jackloves111/9/refs/heads/master/requirements.txt|g' docker/Dockerfile

      - 
        name: Build Image
        uses: docker/build-push-action@v2
        with:
          context: docker
          file: docker/Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/the-movies-tool:latest
            ${{ secrets.DOCKER_USERNAME }}/the-movies-tool:${{ env.app_version }}
